# Site settings
title: Daltoniam
email: daltoniam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All things Dalton related.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daltoniam.com" # the base hostname & protocol for your site
twitter_username: daltoniam
github_username:  daltoniam

# Build settings
markdown: kramdown
